name: Run autotests


on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Select tests to run
        required: true
        default: all
        type: choice
        options:
         - all


jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Copy source code
        uses: actions/checkout@v4
      - name: Set up Puthon env
        uses: actions/setup-python@v5
        with: 
          python-version: "3.9"
      - name: install dependenciesV2
        run: pip install pytest
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest -v
